### ISSUE TITLE
Parallelized training for R GBM

### ISSUE THREAD

**Issue by entelechie** [gbm-developers/gbm#20]
My name is Sheng. I work for A9.com (an Amazon subsidiary). My officemate has contributed the pairwise loss[0] for GBM and we still actively use the library internally.
We have an internal version of GBM with parallelized training implemented, which brings 5-8 times speed-up and enabled training on twenty million samples.
The change is done on the top of [1]. It is fully backward compatible.

Do you think it makes sense to submit our internal version to mainline? 
The commit we forked is newer than current mainline, which has some changes like adding const decorations on function arguments. 

Please instruct me how to proceed. I already got an approval to submit codes.

[0] https://github.com/gbm-developers/gbm/blob/master/src/pairwise.cpp#L3
[1] https://github.com/gbm-developers/gbm3/commit/e41e0e5c91f89ff7a956925174e946fc6f865dd0

**Comment by bgreenwell** [comment]
Sorry for the delayed response. You are more than welcome to make a pull request, provided the package remains backward compatible!
