### ISSUE TITLE
Debian bug report

### ISSUE THREAD

**Issue by harrysouthworth** [gbm-developers/gbm#21]
This was just brought to my attention. It regard version 2.1.1 and the post is about 2.5 years old.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805395

**Comment by bgreenwell** [comment]
Thanks for digging this up. I was made aware that the old `gbm` has a few issues with multinomial support. I plan to come back to this after I'm done teaching for the semester in April!

**Comment by gregridgeway** [comment]
Unlikely to be resolved. Multinomial simply issues a warning to be beware
