### ISSUE TITLE
pairwise examples broke in 2.1.4, they work in 2.1.3

### ISSUE THREAD

**Issue by xelax** [gbm-developers/gbm#27]
Just running the example in https://github.com/gbm-developers/gbm/blob/master/demo/pairwise.R
you get following error when running the pairwise models:

```
Error in if (!is.element(distribution$name, getAvailableDistributions())) { : 
  argument is of length zero
```

reverting to 2.1.3 fixes the error

**Comment by bgreenwell** [comment]
@xelax thanks for reporting! Should be [fixed](https://github.com/gbm-developers/gbm/blob/master/NEWS.md) in the development version now. Can you confirm?

**Comment by xelax** [comment]
It works now! thank you for the very quick turnaround.

**Comment by xelax** [comment]
are you planning to releaser 2.1.5 anytime soon? I'd like to move my scripts to a released version rather than the dev one.

**Comment by bgreenwell** [comment]
@xelax Yep, we are planning to release within a week or so!
