### ISSUE TITLE
Error in Quantile Regression 

### ISSUE THREAD

**Issue by Quaterion** [gbm-developers/gbm#29]
I am using the version 2.1.4 of the gbm package. Specifying the quantile as it is described in the documentation (distribution = list(name = 'quantile', alpha = 0.25)) gives an error. See the example below: 

    library(gbm)

    #the data is genrated using the example from the official documentation page 9 https://cran.r-project.org/web/packages/gbm/gbm.pdf 
    # Simulate data
    set.seed(101) # for reproducibility
    N <- 1000
    X1 <- runif(N)
    X2 <- 2 * runif(N)
    X3 <- ordered(sample(letters[1:4], N, replace = TRUE), levels = letters[4:1])
    X4 <- factor(sample(letters[1:6], N, replace = TRUE))
    X5 <- factor(sample(letters[1:3], N, replace = TRUE))
    X6 <- 3 * runif(N)
    mu <- c(-1, 0, 1, 2)[as.numeric(X3)]
    SNR <- 10 # signal-to-noise ratio
    Y <- X1 ^ 1.5 + 2 * (X2 ^ 0.5) + mu
    sigma <- sqrt(var(Y) / SNR)
    Y <- Y + rnorm(N, 0, sigma)
    X1[sample(1:N,size=500)] <- NA # introduce some missing values
    X4[sample(1:N,size=300)] <- NA # introduce some missing values
    data <- data.frame(Y, X1, X2, X3, X4, X5, X6)

    #Fit a GBM
	model <- gbm(Y ~ . ,data = data,distribution = list(name = 'quantile', alpha = 0.25),n.trees = 100,
                  shrinkage = 0.01, interaction.depth = 4)

This call of the gbm function gives the error...

    Error in if (!is.element(distribution$name, getAvailableDistributions())) { : 
      Argument has length 0

**Comment by bgreenwell** [comment]
@Quaterion thanks for reporting! This should've been fixed as part of [this issue](https://github.com/gbm-developers/gbm/issues/27). Can you try it again using the current development version on GitHub to confirm?

```r
install.packages("devtools")
devtools::install_github("gbm-developers/gbm")

library(gbm)

#the data is genrated using the example from the official documentation page 9 https://cran.r-project.org/web/packages/gbm/gbm.pdf 
# Simulate data
set.seed(101) # for reproducibility
N <- 1000
X1 <- runif(N)
X2 <- 2 * runif(N)
X3 <- ordered(sample(letters[1:4], N, replace = TRUE), levels = letters[4:1])
X4 <- factor(sample(letters[1:6], N, replace = TRUE))
X5 <- factor(sample(letters[1:3], N, replace = TRUE))
X6 <- 3 * runif(N)
mu <- c(-1, 0, 1, 2)[as.numeric(X3)]
SNR <- 10 # signal-to-noise ratio
Y <- X1 ^ 1.5 + 2 * (X2 ^ 0.5) + mu
sigma <- sqrt(var(Y) / SNR)
Y <- Y + rnorm(N, 0, sigma)
X1[sample(1:N,size=500)] <- NA # introduce some missing values
X4[sample(1:N,size=300)] <- NA # introduce some missing values
data <- data.frame(Y, X1, X2, X3, X4, X5, X6)

#Fit a GBM
model <- gbm(Y ~ . ,data = data,distribution = list(name = 'quantile', alpha = 0.25),n.trees = 100,
              shrinkage = 0.01, interaction.depth = 4)
```

**Comment by AvikDalal** [comment]
@bgreenwell Thanks for the update about development version. I had some issues around R tools versions but once I sorted that, dev gbm worked fine on quantile regression. 
`library(devtools)
assignInNamespace("version_info", c(devtools:::version_info, list("3.5" = list(version_min = "3.3.0", version_max = "99.99.99", path = "bin"))), "devtools")
find_rtools() # this shoudl be TRUE
devtools::install_github("gbm-developers/gbm")`

**Comment by AvikDalal** [comment]
@bgreenwell  Thanks for update. Quantile regression is working fine with the dev package.
`library(devtools)
assignInNamespace("version_info", c(devtools:::version_info, list("3.5" = list(version_min = "3.3.0", version_max = "99.99.99", path = "bin"))), "devtools")
find_rtools() # this shoudl be TRUE
devtools::install_github("gbm-developers/gbm")`

**Comment by AvikDalal** [comment]
@bgreenwell Thanks for the update!Quantile Regression is working now with the new dev package. 

Only challenge was some R tools compatibility issues, but once I sorted that, it worked perfect.

```R
library(devtools)
assignInNamespace("version_info", c(devtools:::version_info, list("3.5" = list(version_min = "3.3.0", version_max = "99.99.99", path = "bin"))), "devtools")
find_rtools() # this shoudl be TRUE
devtools::install_github("gbm-developers/gbm")

# load gbm library
library(gbm)
library(mlbench)

data(BostonHousing)

# fit a gbm model with quantile regression

gbm.n.trees <- 200
gbm.model <- gbm(medv~., 
                 data=BostonHousing,
                 distribution=list(name="quantile",alpha=0.6),
                 n.trees = gbm.n.trees,
                 interaction.depth = 1,
                 n.minobsinnode = 10,
                 shrinkage = 0.1,
                 bag.fraction = 0.5,
                 train.fraction = 1.0,
                 verbose=FALSE)
```
