### ISSUE TITLE
cv.threshold definition

### ISSUE THREAD

**Issue by ctlamb** [gbm-developers/gbm#33]
Hello, I am using GBM to created boosted regression trees for species distribution modelling, I then predict these models onto raster stacks, and classify this continuous raster into presence/absence using a threshold.

I have been trying to find a definition of cv.threshold (MODEL$cv.statistics$cv.threshold), as I think that is what I want to use as my threshold. But can't seem to find any definitions. Aside from mention in this [paper ](https://onlinelibrary.wiley.com/doi/pdf/10.1002/ece3.3847)

Thanks

**Comment by bgreenwell** [comment]
Hi @ctlamb, I am not familiar with this statistic and in fact I don't even think it's part of the **gbm** package. Do you have some example code? Are you by chance using the [dismo](https://cran.r-project.org/package=dismo)?

**Comment by bgreenwell** [comment]
You can see how it's computed here: https://github.com/cran/dismo/blob/master/R/gbm.step.R

**Comment by ctlamb** [comment]
Oops, thanks!
