### ISSUE TITLE
plot.it option in gbm.perf function

### ISSUE THREAD

**Issue by cutedou** [gbm-developers/gbm#34]
In the latest version of GBM package (2.1.4), the 'plot.it' option in the 'gbm.perf' function doesn't take effect . Both 'FALSE' and 'TRUE' generates the performance measurement plot.

**Comment by bgreenwell** [comment]
@cutedou thanks for catching, should be an easy fix!

**Comment by bgreenwell** [comment]
Fixed in the dev version!
