### ISSUE TITLE
Explanation of distribution="pairwise"

### ISSUE THREAD

**Issue by victorz-ca** [gbm-developers/gbm#39]
Would it be possible to provide a reference for the distribution="pairwise" option in gbm?

Judging from a recent question in StackExchange, I am not the only one trying to understand this feature? See [https://stats.stackexchange.com/questions/405224/what-does-pairwise-distribuion-in-the-r-gbm-package-mean](url)

**Comment by bgreenwell** [comment]
No problem, sorry for the delay:

C. Burges (2010). “From RankNet to LambdaRank to LambdaMART: An Overview,” Microsoft Research Technical Report MSR-TR-2010-82.
