### ISSUE TITLE
Cross-validation error: "factor level [2] is duplicated"

### ISSUE THREAD

**Issue by victorz-ca** [gbm-developers/gbm#40]
I run into a cv error. Here is the R code (I am following the example in https://www.linkedin.com/pulse/understanding-gradient-boosting-machines-harshdeep-singh/)

#------------ R code -----------------------------------------------------
#-- Download train.csv from https://www.kaggle.com/c/titanic/data

require(caret, quietly = TRUE )
require(gbm)

TrainALL = read.csv("TitanicSurv_byKaggle.csv")
#-- Note: strings are read as factors

set.seed(77850)
inTrain = createDataPartition(y = TrainALL$Survived, 
                              p = 750/891, list = FALSE)

Test = TrainALL[-inTrain,]
Train = TrainALL[inTrain,]

#------------------------------------------------
set.seed(98)
SimpleGBM = gbm( Survived ~ . - PassengerId - Name - Ticket,
                 distribution = "bernoulli",
                 data = Train,
                 n.trees = 1000 , interaction.depth = 4, shrinkage = .01)

#-----------------------------------------------
set.seed(7668)
SimpleGBM_cv = gbm( Survived ~ . - PassengerId - Name - Ticket,
                    distribution = "bernoulli",
                    data = Train,
                    n.trees = 100 , 
                    interaction.depth = 4, shrinkage = .01,
                    cv.folds=3)

#------------------------------------------------
\# Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
\#   factor level [2] is duplicated

**Comment by victorz-ca** [comment]
About the error in CV. In the source data Train has levels:
> levels(Train$Embarked)
[1] ""  "C" "Q" "S"
By changing the null level as follows:
> levels(Train$Embarked)[1]="N"
the code runs.

**Comment by victorz-ca** [comment]
I closed the Issue too soon...

**Comment by victorz-ca** [comment]
Changing Train$Sex to numeric yields a different error:
#------------------------------------------------
Train2 = Train
Train2$Sex = as.numeric(Train$Sex)

set.seed(7668)
SimpleGBM_cv = gbm( Survived ~ . - PassengerId - Name - Ticket,
                 distribution = "bernoulli",
                 data = Train2,
                 n.trees = 1000 , 
                 interaction.depth = 4, shrinkage = .01,
                 cv.folds=3)
#-----------------------------------------------
\# Error in object$var.levels[[i]] : subscript out of bounds

**Comment by hile19** [comment]
try "cv_fold  = 3"

**Comment by ghost** [comment]
Hy, I ran into the same error working with the package geoGAM.

It would be nice if you could fix this error. 
Thanks in advance!

#------------ R code -----------------------------------------------------

#Working with berne and berne.grid from the package geoGAM

#Continuous response
d.ph10 <- berne[berne$dataset == "calibration" & !is.na(berne$ph.0.10), ]
d.ph10 <- d.ph10[complete.cases(d.ph10[13:ncol(d.ph10)]), ]
#Covariates
l.covar <- names(d.ph10[, 13:ncol(d.ph10)])
#------------------------------------------------
#create a grid of the tuning parameters to be tested
gbm.grid <- expand.grid(
  interaction.depth = c(2,5,10,15,20),
  n.trees = seq(2,250, by = 5),
  shrinkage = 0.1, n.minobsinnode = 10)
#------------------------------------------------
set.seed(42)
#------------------------------------------------
#train the gbm model
gbm.model <- train(x=d.ph10[, l.covar ],
                   y=d.ph10[, "ph.0.10"],
                   method = "gbm",
                   tuneGrid = gbm.grid,
                   verbose = FALSE,
                   trControl = trainControl(
                     method = "cv", number = 10,
                     savePredictions = "final"))
#------------------------------------------------
data("berne.grid")
berne.grid$pred <- predict.train(gbm.model, newdata = berne.grid)
#------------------------------------------------
Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
  factor level [5] is duplicated
Called from: factor(x[, i], levels = object$var.levels[[i]])

**Comment by bgreenwell** [comment]
Thanks @AdrianHoch, I’ll take a look as soon as I can. Unfortunately the next few weeks are rather hectic, so not sure exactly when. Will keep you posted.

**Comment by ghost** [comment]
Dear Brandon

Thanks for your quick reply!
Looking forward to hear from you again.

Kind regards
Adrian

Von: Brandon Greenwell <notifications@github.com>
Gesendet: Donnerstag, 23. April 2020 13:45
An: gbm-developers/gbm <gbm@noreply.github.com>
Cc: Hochreutener Adrian (hoce) <hoce@zhaw.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [gbm-developers/gbm] Cross-validation error: "factor level [2] is duplicated" (#40)


Thanks @AdrianHoch<https://github.com/AdrianHoch>, I’ll take a look as soon as I can. Unfortunately the next few weeks are rather hectic, so not sure exactly when. Will keep you posted.

**Comment by bgreenwell** [comment]
@AdrianHoch this should be fixed in the latest patch (will soon make its way to CRAN).

**Comment by ckiefer** [comment]
> @AdrianHoch this should be fixed in the latest patch (will soon make its way to CRAN).
We are running into the same issue with gbm_2.1.5. Sorry my dumb question, where can we get the patched version from? When will there be an updated version in Cran?

**Comment by bgreenwell** [comment]
@ckiefer Patched version is here on GitHub:
```r
if (!requireNamespace("remotes")) {
  install.packages("remotes")
}
remotes::install_github("gbm-developers/gbm")
```

Should make its way to CRAN in the next week or so, just working on a couple issues. Let me know if you still have the same issue.
