### ISSUE TITLE
Is the error outputed by gbm a sum squared error or mean squared error?

### ISSUE THREAD

**Issue by vtao1989** [gbm-developers/gbm#43]
Hi all,

I am trying to understand the error outputed by the gbm package. Is that a mean squared error or a sum squared error? For exmaple, cv.error.

Is there anybody having an idea about this?

Thanks.

**Comment by bgreenwell** [comment]
Hi @vtao1989 whenever `distribution = "gaussian"` the deviance should reflect the MSE. You can see this in the [source code](https://github.com/gbm-developers/gbm/blob/master/src/gaussian.cpp) and also on page 10 of the vignette; `browseVignettes("gbm")`.

**Comment by vtao1989** [comment]
@bgreenwell Thanks.
