### ISSUE TITLE
Memory leak in GBM

### ISSUE THREAD

**Issue by leopreuss** [gbm-developers/gbm#46]
I am facing an issue related to memory leak with GBM. When I run it too many times, it seems GBM does not releases memory when it completes running. I tried running gc() but it does not deallocate memory and reports fewer allocated memory than rsession process on Task Manager.

I'm using Windows 10 x64, R 3.6.1 and RStudio 1.2.1335.
GBM version is 2.1.5.

The example below causes the problem:
`library(gbm)

m <- matrix(sample(1:10, 20000, T), nrow = 10000, ncol = 2)
d <- data.frame(m, r = as.factor(round(runif(nrow(m), 1, 3))))

for (i in 1:1000){gbm(r ~ ., data = d, distribution = 'multinomial', keep.data = F)}`

When running this code on RStudio, rsession process increases memory indefinitely.

**Comment by gregridgeway** [comment]
Great catch! I've moved these new/deletes to InitF/destructor so that they are allocated/deallocated once, not repeatedly called within the boosting iterations (very expensive otherwise!)
