### ISSUE TITLE
data making trained GBM model very heavy

### ISSUE THREAD

**Issue by meetjivani** [gbm-developers/gbm#47]
Hello team,

We are using GBM model to train on really voluminous data ~15GB. The trained model size becomes huge ~17GB. In the trained model we see data saved along with trees and other model details, taking around 96% of total model size.

Is there any use of data in trained model, specifically for prediction purpose.

**Comment by bgreenwell** [comment]
Hi @meetjivani, try setting ‘keep.data = FALSE’ when you call ‘gbm()’.

**Comment by bgreenwell** [comment]
And I think the only use of keeping the data is that potential calls to ‘gbm.more()’ will be faster.

**Comment by meetjivani** [comment]
@bgreenwell thanks for the confirmation. We did little differently, by keeping keep.data=TRUE for entire training, so that data logistics is not impacted between subsequent iterations. But once training is done, we are setting the model$data parameter to NULL to reduce the model size before saving. We don't have to further train the model, using GBM.MODEL()

Do you see any shortcomings doing this.

**Comment by bgreenwell** [comment]
Nope, unless you need predictions for specific training observations in the future and you don't plan on keeping the data around!

**Comment by meetjivani** [comment]
thanks @bgreenwell. Appreciate the help.
