### ISSUE TITLE
gbm issue installation R

### ISSUE THREAD

**Issue by isisarantes** [gbm-developers/gbm#54]
Hi,
I was using biomod2 before and it was working just fine. Now when I try to run a gbm model using BIOMOD_ModelingOptions/ BIOMOD_Modeling it crashes R. 

So, I decided to update R and all packages. When I try install biomod2, it requires the update of gbm package from 2.1.5 to 2.1.8. However, it doesn't work in my computer and I'm finding the error in the pics attached.

![Screen Shot 2020-07-17 at 3 28 38 PM](https://user-images.githubusercontent.com/10964418/87828330-52287000-c842-11ea-9d2b-609f60c4c961.png)
![Screen Shot 2020-07-17 at 3 27 56 PM](https://user-images.githubusercontent.com/10964418/87828333-53599d00-c842-11ea-9af5-640c57fd006e.png)

Any help with this issue? 
Thank you,
Ísis

**Comment by bgreenwell** [comment]
Hi @isisarantes, unfortunately it's hard to say what the issue is. Can you try installing the development version directly from GitHub?
```r
if (!requireNamespace("remotes")) {
  install.packages("remotes")
}
remotes::install_github("gbm-developers/gbm")
```
