### ISSUE TITLE
Package version check from DESCRIPTION does not work

### ISSUE THREAD

**Issue by SOFROGE1** [gbm-developers/gbm#56]
Hello,

I am facing the following issue: 
Normally when you I have in the metadata DESCRIPTION of my project a specific version minimum (>=), when an older version is installed, I have a message stopping the building process and telling me that the version is outdated. See the example below:

_Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘lubridate’ 1.7.4 is being loaded, but >= 1.7.5 is required
Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted_

Now, in my machine I have gbm 2.1.5 and I have specified in the DESCRIPTION >=2.1.8
Nevertheless, the building goes on, without any error message and finishes successfully. The installed package remains 2.1.5 (like it has never gone through the requirement).

Any insight on this issue? Many thanks in advance,

**Comment by bgreenwell** [comment]
Hi @SOFROGE1, not sure this is actually an issue with **gbm**. The current CRAN release is 2.1.8, so there must be something happening in your workflow?
