### ISSUE TITLE
Warning message when gbm distribution is a list

### ISSUE THREAD

**Issue by miguellacerda** [gbm-developers/gbm#57]
When a list is provided to the `distribution` parameter in the `gbm` function, an (annoying) warning message is produced:

```
Warning message:
In if (object$distribution == "multinomial") { :
  the condition has length > 1 and only the first element will be used
```

I think this could easily be avoided by changing the if statement to:

`if (object$distribution[1] == "multinomial"){...}`

**Comment by bgreenwell** [comment]
Thanks @miguellacerda, I'll look into it soon!
