### ISSUE TITLE
Suggestion to clarify an error message

### ISSUE THREAD

**Issue by rachaelvp** [gbm-developers/gbm#59]
Hello, 

I was getting this error when trying to run `gbm.fit`: 
`The data set is too small or the subsampling rate is too large: nTrain * bag.fraction <= n.minobsinnode`. 

I modified my arguments to ensure `nTrain * bag.fraction > n.minobsinnode`. However, I was still getting the error. Upon closer examination of the source code, I see [here](https://github.com/gbm-developers/gbm/blob/18e595597e19c289328f5eb0b73945a1ea72fc7d/R/gbm.fit.R#L248) that the error is generated when `nTrain * bag.fraction <= 2 * n.minobsinnode + 1`. This error is different that the one reported in the message, so I suggest correcting the inequality in the error message.

**Comment by gregridgeway** [comment]
Fixed in 2.2.0
