### ISSUE TITLE
Warning message when the distribution is set to multinomial

### ISSUE THREAD

**Issue by Epimorpha1** [gbm-developers/gbm#62]
Hi, can you please advise me what to do when running gbm with categorical response variables and when the distribution is set to multinomial. When assuming a multinomial distribution this message is displayed: 

> "distribution = "multinomial"' is ill-advised as it is currently broken. It exists only for backwards compatibility. Use at your own risk.

What specifically is "broken" and can the results from the gbm be trusted?

**Comment by gregridgeway** [comment]
We never felt confident that the multinomial code was doing the right thing. There were a number of odd results that we decided to add the message. Then development moved over to gbm3 and we never went back to focus on multinomial again
