### ISSUE TITLE
Remove RUnit as a Suggested dependency?

### ISSUE THREAD

**Issue by MichaelChirico** [gbm-developers/gbm#63]
It doesn't look like it's used anymore.

Happy to file a clean-up PR, but I don't know if it's being kept for some reason.

**Comment by bgreenwell** [comment]
Hi @MichaelChirico, **RUnit** is actually still used in the [test.gbm()](https://github.com/gbm-developers/gbm/blob/master/R/test.gbm.R) function that ships with the package.

**Comment by MichaelChirico** [comment]
Ah right. I don't know why I checked the NAMESPACE, Suggests won't show up there.
