### ISSUE TITLE
Error in 1: trees : argument of length 0

### ISSUE THREAD

**Issue by SumantraChatterjee** [gbm-developers/gbm#65]
To whom it may concern

I am using the R-package "gbm" to use "Generalized Boosted Regression Models" for my research. Whenever I run this program in one loop only, it gives me exciting results in very little time (far faster than the one in CARET). However, when I am trying to run multiple loops on this (gbm) I am getting an error message "argument of length zero". 

Now, I googled the origin of this error code, and everyone mentions that an "empty data object" is being used in the loop, and it is being originated from the line "n.trees". 

I couldn't figure out how this error is appearing. I believe the default for n.trees is 100, correct? I have tried with several different numbers. However, I have failed to resolve this issue. So I thought of reaching out to you if you could guide/advise me on how to resolve this error. Thanks

Here is the syntax that I used. Please let me know. 

library(e1071)
library(tidyverse)      
for (r in 1:100){
gbm=gbm(
            Y~.,
            distribution = "gaussian",
            data = data_train,
            #weights,
            var.monotone = NULL,
            n.trees = 1000,
            interaction.depth = 1,
            n.minobsinnode = 10,
            shrinkage = 0.1,
            bag.fraction = 0.5,
            train.fraction = 1,
            cv.folds = 1,
            keep.data = TRUE,
            verbose = FALSE,
            class.stratify.cv = NULL,
            n.cores = NULL
  )
}

Sending the data will be difficult as it is research data, and would require lots of permissions and paperwork. 

Thank you for your help.

**Comment by gregridgeway** [comment]
Can you send the code that actually generates the error?The subject line says "1:trees" but that doesn't show up in your code below.Your loop below uses "r"Do not name the object gbm. That seems ripe for causing a bug. Prefer something like gbm1 <- gbm( and all the arguments) Greg
-------- Original message --------From: samchatterman ***@***.***> Date: 8/24/22  6:59 PM  (GMT-05:00) To: gbm-developers/gbm ***@***.***> Cc: Subscribed ***@***.***> Subject: [gbm-developers/gbm] Error in 1: trees : argument of length 0 (Issue
  #65) 
To whom it may concern
I am using the R-package "gbm" to use "Generalized Boosted Regression Models" for my research. Whenever I run this program in one loop only, it gives me exciting results in very little time (far faster than the one in CARET). However, when I am trying to run multiple loops on this (gbm) I am getting an error message "argument of length zero".
Now, I googled the origin of this error code, and everyone mentions that an "empty data object" is being used in the loop, and it is being originated from the line "n.trees".
I couldn't figure out how this error is appearing. I believe the default for n.trees is 100, correct? I have tried with several different numbers. However, I have failed to resolve this issue. So I thought of reaching out to you if you could guide/advise me on how to resolve this error. Thanks
Here is the syntax that I used. Please let me know.
library(e1071)
library(tidyverse)
for (r in 1:100){
gbm=gbm(
Y~.,
distribution = "gaussian",
data = data_train,
#weights,
var.monotone = NULL,
n.trees = 1000,
interaction.depth = 1,
n.minobsinnode = 10,
shrinkage = 0.1,
bag.fraction = 0.5,
train.fraction = 1,
cv.folds = 1,
keep.data = TRUE,
verbose = FALSE,
class.stratify.cv = NULL,
n.cores = NULL
)
}
Sending the data will be difficult as it is research data, and would require lots of permissions and paperwork.
Thank you for your help.

**Comment by SumantraChatterjee** [comment]
My apologies, **1:trees** must have been a typo. I meant **n.trees**. Sorry for the inconvenience caused.

**Comment by gregridgeway** [comment]
But I also do not see 1:n.trees in the code eitherGreg
-------- Original message --------From: samchatterman ***@***.***> Date: 8/24/22  7:48 PM  (GMT-05:00) To: gbm-developers/gbm ***@***.***> Cc: Greg Ridgeway ***@***.***>, Comment ***@***.***> Subject: Re: [gbm-developers/gbm] Error in 1: trees : argument of length 0
  (Issue #65) 
My apologies, 1:trees must have been a typo. I meant n.trees. Sorry for the inconvenience caused.

**Comment by bgreenwell** [comment]
Hi @samchatterman, debugging issues like this can be pretty challenging and time consuming without the ability to run a [reproducible example](https://reprex.tidyverse.org/). Could you kindly reproduce with a different data set that you can share (e.g., from the **mlbench** or **modeldata** packages) and post the example code in its entirety to this thread so that we can run it on our end?

**Comment by SumantraChatterjee** [comment]
I just created some dummy data, no relation to my research data and attaching as CSV file. Hope this will help?
[FAKEDATA.csv](https://github.com/gbm-developers/gbm/files/9427285/FAKEDATA.csv)

**Comment by SumantraChatterjee** [comment]
Ok. I was digging more, and if this help you guys to pinpoint the issue- if I run GBM by itself (even if I run in a loop) the issue does not arise. However, it arises when I use GBM with more regression models. So here is the modified code:

library(e1071)
library(tidyverse)
library(caret)
library(glmnet)



custom <- trainControl(method= "repeatedcv",
                       number=10,
                       repeats = 5,
                       verboseIter = T)



for (r in 1:10) {
  
  
  
  ind <- createDataPartition(data$Y, p=0.7, list=F)
  
  data_train <- data[ind,]
  data_test <- data[-ind,]
  
  
  #LM#
    start_time <- Sys.time()
    lm <- train(Y~.,
              data_train,
              method= 'lm',
              trControl= custom)
  

  
  
  
  #Ridge#
  start_time <- Sys.time()
  ridge <- train(Y~.,
                 data_train,
                 method = 'glmnet',
                 tuneGrid= expand.grid(alpha=0,
                                       lambda = seq(0.0001,1, length=5)),
                 trControl= custom)
  end_time <- Sys.time()
  time_2=start_time-end_time

 
  
  #Lasso#
  start_time <- Sys.time()
  lasso <- train(Y~.,
                 data_train,
                 method = 'glmnet',
                 tuneGrid= expand.grid(alpha=1,
                                       lambda = seq(0.0001,1, length=5)),
                 trControl= custom)
  end_time <- Sys.time()
  time_3=start_time-end_time
  
 
  
  varImplasso <- varImp(lasso, scale = T)$importance
  varImplasso[,2] <- rownames(varImplasso)
  lasso_varImp[[r]]<- list(varImplasso)
  
  
  
  #EN#
  start_time <- Sys.time()
  en <- train(Y~.,
              data_train,
              method = 'glmnet',
              tuneGrid= expand.grid(alpha=seq(0,1, length=10),
                                    lambda = seq(0.0001,1, length=5)),
              trControl= custom)
  end_time <- Sys.time()
  time_4=start_time-end_time
  
  
  
  
  #RF#
  start_time <- Sys.time()
  #tunegridrf <- expand.grid(.mtry=c(1:50))
  rf <- randomForest(x = data_train[-7],
                        y = data_train$Y,
                        ntree = 1000,
                        random_state = 0
                        )
  end_time <- Sys.time()
  time_5=start_time-end_time
  
  
  
  
  #GBM#
  
  
  start_time <- Sys.time()

    
    ind <- createDataPartition(data$Y, p=0.7, list=F)
    
    data_train <- data[ind,]
    data_test <- data[-ind,]
    gbm=gbm(
      Y~.,
      distribution = "gaussian",
      data = data_train,
      #weights,
      var.monotone = NULL,
      n.trees = 1000,
      interaction.depth = 1,
      n.minobsinnode = 10,
      shrinkage = 0.1,
      bag.fraction = 0.5,
      train.fraction = 1,
      cv.folds = 1,
      keep.data = TRUE,
      verbose = FALSE,
      class.stratify.cv = NULL,
      n.cores = NULL
    )
    
    
  end_time <- Sys.time()
  time=start_time-end_time
  
  
}

**Comment by gregridgeway** [comment]
And what is the error message? Can you cut-and-paste the complete error message?

**Comment by SumantraChatterjee** [comment]
This the error message

Using 1000 trees...

Using 1000 trees...

Error in 1:n.trees : argument of length 0
