### ISSUE TITLE
Problems with bernoulli response silently ignored

### ISSUE THREAD

**Issue by mikkoku** [gbm-developers/gbm#70]
I was wondering why gbm didn't give any prediction for my classification problem. Found out that I had tried 2 wrong ways of specifying the response, and in both cases the problem was silently ignored.
For example 2 of the following silently ignore the problem and state that no variable had non-zero influence.
```
gbm(y ~ ., data=data.frame(y=factor(rep(c(0,1), 100)), x=1:2)) # silently broken, should work
gbm(y ~ ., data=data.frame(y=factor(rep(c(1,2), 100)), x=1:2)) # Errors, should work
gbm(y ~ ., data=data.frame(y=rep(c(1,2), 100), x=1:2)) # silently broken, should error?
gbm(y ~ ., data=data.frame(y=rep(c(0,1), 100), x=1:2)) # OK
```

https://github.com/gbm-developers/gbm/blob/90c871133a226f73d235b82823bab691119844c8/R/gbm.fit.R#L317-L324

Similar problems probably with adaboost and huberized responses, which I think should share the same logic.

**Comment by bgreenwell** [comment]
Thanks @mikkoku, I’ll take a close look shortly.

**Comment by gregridgeway** [comment]
Version 2.2.0 now should give errors on bernoulli, adaboost, huberized if the outcome is not numeric and in {0,1}
