### ISSUE TITLE
single tree dendrogram visualization

### ISSUE THREAD

**Issue by abrahamroseman** [gbm-developers/gbm#73]
Is there a way to easily extract a dendrogram from a single tree extracted from the model? I believe there is a similar diagram in Jane Elith's paper using BRT.

**Comment by gregridgeway** [comment]
pretty.gbm.tree() will give you the information you need to create the tree. The gbm package does not draw the tree itself. Check out the help ?pretty.gbm.tree to see how to interpret the output.

 

I should also add that the individual tree is really not very interesting. It’s just a basis function. It would be like drawing just one of a spline’s basis functions. It’s not really interesting on its own without all the other terms.

 

Greg

 

From: abrahamroseman ***@***.***> 
Sent: Wednesday, February 15, 2023 10:24 PM
To: gbm-developers/gbm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gbm-developers/gbm] single tree dendrogram visualization (Issue #73)

 

Is there a way to easily extract a dendrogram from a single tree extracted from the model? I believe there is a similar diagram in Jane Elith's paper using BRT.

**Comment by abrahamroseman** [comment]
I noticed pretty.gbm.tree didn’t seem to produce a decision tree instead some sort of basis function.

I was thinking more of how to write down a single decision tree.

**Comment by gregridgeway** [comment]
It does produce a decision tree. And that decision tree is a basis function. It’s just that pretty.gbm.tree() doesn’t draw a pretty picture of a decision tree. Have a look at ?pretty.gbm.tree so that you can interpret the output so that you can draw the tree based on the output.

**Comment by bgreenwell** [comment]
@abrahamroseman, I’ve come across some solutions in the past; for example, see this post: https://www.justinsingh.me/post/2020-12-04-visualizing-gbm-trees-in-r/

**Comment by abrahamroseman** [comment]
Thanks. I saw this before but implemented it incorrectly, but now was able to run it correctly. 

However, I'm not sure about something when i view the plot. The prediction seems to make decisions based on different values. For example, in the image below it goes one way when less than 153 and another way when great than 0.38, which doesn't quite make sense.
<img width="474" alt="截屏2023-02-19 下午9 38 22" src="https://user-images.githubusercontent.com/96634027/220004059-ecc60960-a733-461b-8074-70433319cd88.png">
