### ISSUE TITLE
old gbm 1.x code?

### ISSUE THREAD

**Issue by apiskors** [gbm-developers/gbm#76]
The history in this Git repository seems to start 2013-01-25, approximately when work on gbm 2.0 started.
The last 1.x tarball, gbm_1.6-3.2.tar.gz, dates from 2012-12-09.
Does the version control history for gbm 1.x exists anywhere?  Or are the old tarballs on CRAN the best we have for 1.x?

https://cran.r-project.org/src/contrib/Archive/gbm/

**Comment by gregridgeway** [comment]
I found versions going back to gbm0.1 (around 1999). 
https://drive.google.com/drive/folders/0B2CD6T-u0yNWYVBJUHVmZWFnMFk?resourcekey=0-qFXulYHwLiCwrYr3ImcW_Q&usp=sharing
If you're looking for something specific, then maybe I can help you find it
