### ISSUE TITLE
Consider supporting -DR_NO_REMAP

### ISSUE THREAD

**Issue by michaelquinn32** [gbm-developers/gbm#77]
Changes to the LLVM compiler introduce errors when compiling gbm. The transitive dependency between <vector> and <locale> is being removed, which leads to errors like this:

```
include/c++/v1/locale:3226:31: error: no member named 'Rf_error' in 'std::codecvt_base'
 3226 |           __r = codecvt_base::error;
      |                 ~~~~~~~~~~~~~~^
R/src/include/R_ext/Error.h:52:15: note: expanded from macro 'error'
   52 | #define error Rf_error
```

One way to fix this is to use `R_NO_REMAP`. 
https://rstudio.github.io/r-manuals/r-exts/The-R-API.html

But that will require calling error and warning with their `Rf_` prefixed versions instead.
https://github.com/gbm-developers/gbm/blob/20a31ff2e9dcc27572c249869e7c5b2ec64cdb8a/src/node_search.cpp#L149

Thanks!

**Comment by gregridgeway** [comment]
Thanks for finding the error and pointing me to a solution. Much easier to fix than I originally thought.

**Comment by michaelquinn32** [comment]
Awesome! Thanks for the quick fix.

I can confirm that this works against the new LLVM version coming up.

FYI, if you don't want to inline the definitions in the future, you can use a Makevars file to handle you compilation flags.

*  Docs: https://rstudio.github.io/r-manuals/r-exts/Creating-R-packages.html#using-makevars
*  Example: https://github.com/r-lib/commonmark/blob/main/src/Makevars

**Comment by gregridgeway** [comment]
Glad it worked. Thanks for the Makevars tip too.
